### ISSUE TITLE
Labels and Markers Mismatch

### ISSUE THREAD

**Issue by nirabpudasaini** [biplovbhandari/Hydropower#2]
The layer labels mismatches with the markers in the map. When above 100 is on Green Markers are shown in maps and when 25 to 100 is on Blue Markers is shown in the maps.

![hydropowermismatchgreen](https://cloud.githubusercontent.com/assets/3871904/5800343/7258176a-a005-11e4-9388-242bb6a375f8.png)

![hydropowerlayermismatchblue](https://cloud.githubusercontent.com/assets/3871904/5800389/eddee4a4-a005-11e4-9e42-a5cbfeb98798.png)

**Comment by biplovbhandari** [comment]
solved
